### ISSUE TITLE
Question: FinRL_portfolio_allocation_NeurIPS_Training

### ISSUE THREAD

**Issue by M-Colley** [AI4Finance-Foundation/FinRL#155]
Hello, quick question. When I change the timeframe for the training from 

`train = data_split(df, '2009-01-01','2019-01-01')`

to `train = data_split(df, '**2004**-01-01','2019-01-01')`

I get an error in the line: `env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))`

The error is:

```
ValueError                                Traceback (most recent call last)
<ipython-input-188-575def09184a> in <module>()
----> 1 env_train, _ = e_train_gym.get_sb_env()
      2 print(type(env_train))

2 frames
<ipython-input-185-ae50cfabacd8> in get_sb_env(self)
    230     def get_sb_env(self):
    231         e = DummyVecEnv([lambda: self])
--> 232         obs = e.reset()
    233         return e, obs

/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in reset(self)
     60         for env_idx in range(self.num_envs):
     61             obs = self.envs[env_idx].reset()
---> 62             self._save_obs(env_idx, obs)
     63         return self._obs_from_buf()
     64 

/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in _save_obs(self, env_idx, obs)
     90         for key in self.keys:
     91             if key is None:
---> 92                 self.buf_obs[key][env_idx] = obs
     93             else:
     94                 self.buf_obs[key][env_idx] = obs[key]

ValueError: could not broadcast input array from shape (37,29) into shape (38,30)
```

What does this error mean and why is this the case?

**Comment by suppureme** [comment]
I am facing the same issue @XiaoYangLiu-FinRL

**Comment by dwaynepaschall** [comment]
My experience so far is that this error occurs because of another error when computing the covariance matrices. If you watch the 

  covs = return_lookback.cov().values

step, you'll notice some divide by 0 errors. I manually stepped through the loop and found that during the pivot,

  price_lookback = data_lookback.pivot_table(index = 'date',columns = 'tic', values = 'close')

sometimes the price_lookback temp var will have one of the stocks with NaN in the columns. My guess is that sometimes a stock may be missing a closing price print for one of the days the other stocks in the stock list Do have price prints. That's what Im working to try so far anyway. 

I've tried two different data vendors and arrive with the same error:

/home/dwayne/anaconda3/envs/rl/lib/python3.7/site-packages/pandas/core/frame.py:8525: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/home/dwayne/anaconda3/envs/rl/lib/python3.7/site-packages/numpy/lib/function_base.py:2493: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

This will give an unexpected shape to the   cov_list.append(covs) variable. This then generates the error that you (and I) see above.

--Dwayne
