### ISSUE TITLE
Might need to explicitly form DataFrame instead of Series to avoid KeyError: True

### ISSUE THREAD

**Issue by Mahesha999** [AI4Finance-Foundation/FinRL#169]
I was trying out `this_works_1_18.ipynb`. When I specified single stock instead of DOW30, it gave me `KeyError: true`:

![image](https://user-images.githubusercontent.com/4706946/110224843-7cc85580-7f05-11eb-8d0b-73c014909570.png)

I guess the culprit was line:

```
trunc_df = self.df.loc[date]
```
which returns `pandas.Series` when there is a single stock. I guess it should be double brackets to make it consistently return `DataFrame`:

```
trunc_df = self.df.loc[[date]]
```
`KeyError` error vanished after this change. So I guess same will apply to [`StockTradingEnvCashpenalty` line 165](https://github.com/AI4Finance-LLC/FinRL-Library/blob/dffa8d4931dfb2e60b706664f2d8daa182124358/finrl/env/env_stocktrading_cashpenalty.py#L165), right?

However, while continuing to run the notebook, I encountered following error on `model.load()` call :

```
/home/mahesha999/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7fcd16a74e20> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fcd16c15ca0>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
/home/mahesha999/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(

EPISODE|STEPS|TERMINAL_REASON|TOT_ASSETS|TERMINAL_REWARD_unsc|CASH_PCT  
   1| 491|Last Date      |$1001153  |0.00024%  |99.58%    
Eval num_timesteps=1500, episode_reward=0.00 +/- 0.00
Episode length: 492.00 +/- 0.00
New best mean reward!
   3| 491|Last Date      |$1000000  |0.00000%  |100.00%   
Eval num_timesteps=3000, episode_reward=0.00 +/- 0.00
Episode length: 492.00 +/- 0.00
   5| 491|Last Date      |$1000000  |0.00000%  |100.00%   
Eval num_timesteps=4500, episode_reward=0.00 +/- 0.00
Episode length: 492.00 +/- 0.00

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-53a21a75c23f> in <module>
----> 1 model.learn(total_timesteps = 20000, 
      2             eval_env = env_trade,
      3             eval_freq = 250,
      4             log_interval = 1,
      5             tb_log_name = '1_18_lastrun',

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    278     ) -> "PPO":
    279 
--> 280         return super(PPO, self).learn(
    281             total_timesteps=total_timesteps,
    282             callback=callback,

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    245                 logger.dump(step=self.num_timesteps)
    246 
--> 247             self.train()
    248 
    249         callback.on_training_end()

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py in train(self)
    189                     self.policy.reset_noise(self.batch_size)
    190 
--> 191                 values, log_prob, entropy = self.policy.evaluate_actions(rollout_data.observations, actions)
    192                 values = values.flatten()
    193                 # Normalize advantage

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/policies.py in evaluate_actions(self, obs, actions)
    619         """
    620         latent_pi, latent_vf, latent_sde = self._get_latent(obs)
--> 621         distribution = self._get_action_dist_from_latent(latent_pi, latent_sde)
    622         log_prob = distribution.log_prob(actions)
    623         values = self.value_net(latent_vf)

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/policies.py in _get_action_dist_from_latent(self, latent_pi, latent_sde)
    581 
    582         if isinstance(self.action_dist, DiagGaussianDistribution):
--> 583             return self.action_dist.proba_distribution(mean_actions, self.log_std)
    584         elif isinstance(self.action_dist, CategoricalDistribution):
    585             # Here mean_actions are the logits before the softmax

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/stable_baselines3/common/distributions.py in proba_distribution(self, mean_actions, log_std)
    150         """
    151         action_std = th.ones_like(mean_actions) * log_std.exp()
--> 152         self.distribution = Normal(mean_actions, action_std)
    153         return self
    154 

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/torch/distributions/normal.py in __init__(self, loc, scale, validate_args)
     48         else:
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 
     52     def expand(self, batch_shape, _instance=None):

~/.local/share/virtualenvs/stockpipjup-LcEfOh15/lib/python3.8/site-packages/torch/distributions/distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     51                     continue  # skip checking lazily-constructed args
     52                 if not constraint.check(getattr(self, param)).all():
---> 53                     raise ValueError("The parameter {} has invalid values".format(param))
     54         super(Distribution, self).__init__()
     55 

ValueError: The parameter loc has invalid values
```

Any help? Is this resolved in `StockTradingEnvCashpenalty`? Note that I was able to run the notebook fully successfully with DOW30. I added single stock `TCS.NS` instead of DOW30 and I started getting above errors.

**Comment by XiaoYangLiu-FinRL** [comment]
@Mahesha999 Thx. Would like to pull a request to fix it?

**Comment by Mahesha999** [comment]
@XiaoYangLiu-FinRL any quick comment on the last error? Am I missing some basic understanding?

**Comment by Busy2045** [comment]
Hello,

I am running Multiple Stock Trading Using Ensemble Strategy.ipynb and came across the same "ValueError: The parameter loc has invalid values" problem.

When i debug the error, my understandings are as follows:

We try to develop a policy which is a probability distribution(in our case Normal distribution). In order to come to this point, we train DNN to produce logits which is then converted to probability distribution via Softmax to normalize. There is a restriction for Mean of distr. to be Real which is violated for some reason through this -tensor to distribution- conversion hence producing this error. 

I just wonder how Mean of distr. to be non-Real value through this conversion? Any idea on that?


Here is the error & tensorboard log:

============Start Ensemble Strategy============
============================================
nan
turbulence_threshold:  728029.963237278
======Model training from:  2000-01-01 to  2019-01-02
======A2C Training========
{'n_steps': 5, 'ent_coef': 0.01, 'learning_rate': 0.0005}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_10
------------------------------------
| time/                 |          |
|    fps                | 58       |
|    iterations         | 100      |
|    time_elapsed       | 8        |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -35.6    |
|    explained_variance | -0.0519  |
|    learning_rate      | 0.0005   |
|    n_updates          | 99       |
|    policy_loss        | 26.2     |
|    std                | 1        |
|    value_loss         | 3.39     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 58       |
|    iterations         | 200      |
|    time_elapsed       | 17       |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -35.6    |
|    explained_variance | -0.287   |
|    learning_rate      | 0.0005   |
|    n_updates          | 199      |
|    policy_loss        | 25       |
|    std                | 1.01     |
|    value_loss         | 0.938    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 57       |
|    iterations         | 300      |
|    time_elapsed       | 25       |
|    total_timesteps    | 1500     |
| train/                |          |
|    entropy_loss       | -35.6    |
|    explained_variance | 0        |
|    learning_rate      | 0.0005   |
|    n_updates          | 299      |
|    policy_loss        | 124      |
|    std                | 1        |
|    value_loss         | 24.4     |
------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-f7216cfcab9f> in <module>
      2                                                  PPO_model_kwargs,
      3                                                  DDPG_model_kwargs,
----> 4                                                  timesteps_dict)

~\Downloads\FinRL-Library-master\FinRL-Library-master\finrl\model\models.py in run_ensemble_strategy(self, A2C_model_kwargs, PPO_model_kwargs, DDPG_model_kwargs, timesteps_dict)
    337             print("======A2C Training========")
    338             model_a2c = self.get_model("a2c",self.train_env,policy="MlpPolicy",model_kwargs=A2C_model_kwargs)
--> 339             model_a2c = self.train_model(model_a2c, "a2c", tb_log_name="a2c_{}".format(i), iter_num = i, total_timesteps=timesteps_dict['a2c']) #100_000
    340 
    341             print("======A2C Validation from: ", validation_start_date, "to ",validation_end_date)

~\Downloads\FinRL-Library-master\FinRL-Library-master\finrl\model\models.py in train_model(model, model_name, tb_log_name, iter_num, total_timesteps)
    161     @staticmethod
    162     def train_model(model, model_name, tb_log_name, iter_num, total_timesteps=5000):
--> 163         model = model.learn(total_timesteps=total_timesteps, tb_log_name=tb_log_name)
    164         model.save(f"{config.TRAINED_MODEL_DIR}/{model_name.upper()}_{total_timesteps//1000}k_{iter_num}")
    165         return model

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\a2c\a2c.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    197             tb_log_name=tb_log_name,
    198             eval_log_path=eval_log_path,
--> 199             reset_num_timesteps=reset_num_timesteps,
    200         )

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    225         while self.num_timesteps < total_timesteps:
    226 
--> 227             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    228 
    229             if continue_training is False:

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    157                 # Convert to pytorch tensor
    158                 obs_tensor = th.as_tensor(self._last_obs).to(self.device)
--> 159                 actions, values, log_probs = self.policy.forward(obs_tensor)
    160             actions = actions.cpu().numpy()
    161 

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\common\policies.py in forward(self, obs, deterministic)
    535         # Evaluate the values for the given observations
    536         values = self.value_net(latent_vf)
--> 537         distribution = self._get_action_dist_from_latent(latent_pi, latent_sde=latent_sde)
    538         actions = distribution.get_actions(deterministic=deterministic)
    539         log_prob = distribution.log_prob(actions)

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\common\policies.py in _get_action_dist_from_latent(self, latent_pi, latent_sde)
    570 
    571         if isinstance(self.action_dist, DiagGaussianDistribution):
--> 572             return self.action_dist.proba_distribution(mean_actions, self.log_std)
    573         elif isinstance(self.action_dist, CategoricalDistribution):
    574             # Here mean_actions are the logits before the softmax

~\Anaconda3\envs\FinRL\lib\site-packages\stable_baselines3\common\distributions.py in proba_distribution(self, mean_actions, log_std)
    150         """
    151         action_std = th.ones_like(mean_actions) * log_std.exp()
--> 152         self.distribution = Normal(mean_actions, action_std)
    153         return self
    154 

~\Anaconda3\envs\FinRL\lib\site-packages\torch\distributions\normal.py in __init__(self, loc, scale, validate_args)
     48         else:
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 
     52     def expand(self, batch_shape, _instance=None):

~\Anaconda3\envs\FinRL\lib\site-packages\torch\distributions\distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     51                     continue  # skip checking lazily-constructed args
     52                 if not constraint.check(getattr(self, param)).all():
---> 53                     raise ValueError("The parameter {} has invalid values".format(param))
     54         super(Distribution, self).__init__()
     55 

ValueError: The parameter loc has invalid values

[events.out.tfevents.1616274336.DESKTOP-G9ABSN0.4956.zip](https://github.com/AI4Finance-LLC/FinRL-Library/files/6177119/events.out.tfevents.1616274336.DESKTOP-G9ABSN0.4956.zip)

**Comment by Mahesha999** [comment]
@Busy2045 were you able to resolve this error?

**Comment by DishinGoyani** [comment]
@Busy2045 This may help. You can use [VecCheckNan](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecchecknan) to trace where is the issue.

and further you can refer [this][1] also and specifically for `VecCheckNan` [example][2].

In my case after using `VecCheckNan` it show me that my reward was returning `inf` due to bug in reward calculation.

[1]:https://stable-baselines.readthedocs.io/en/master/guide/checking_nan.html#dealing-with-nans-and-infs
[2]:https://stable-baselines.readthedocs.io/en/master/guide/checking_nan.html#vecchecknan-wrapper
