### ISSUE TITLE
questions about data

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#339]
1-Can we use own 30 stocks data? Which notebook must be changed?
2-Do all 30 csv files have to have the same number of rows?

**Comment by Athe-kunal** [comment]
Yeah, you can pass the ticker symbol list for all 30 assets and proceed. 
The final dataframe of the portfolio is arranged as per ticker symbol alphabetical order and date, so for days on which the given asset is not present, it will simply be omitted. So they don't need to be of same length

**Comment by skhonsha** [comment]
great, thanks to reply, I do not mean the list of stock names, but process my own csv files which has already been downloaded

**Comment by skhonsha** [comment]
and data must have "day" column?

**Comment by Athe-kunal** [comment]
You can do a left join of pandas data frames based on the date column. Probably find the CSV file with the highest number of datapoints and left join other ones based on the date column so that you have the complete dataset.
"day" column is not necessary, it can be sent a categorical column for dail_information_cols.

**Comment by skhonsha** [comment]
thanks a lot, when I try to test for single stock, I got "ZeroDivisionError: float division by zero", but for dow30 stocka has no problem, why?
![error](https://user-images.githubusercontent.com/40491703/141514223-3840de24-bde8-4233-be99-6335e466d7d9.png)

**Comment by Athe-kunal** [comment]
Yeah your model has diverged. This maybe due to sub optimal hyperparameters. The default hyperparameters are for DOW Jones hence they work well. You can follow the tutorial Hyperparameter optimization using optuna to get the best set of hyperparameters for your particular set of stocks

https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/Hyperparameter_optimization%20using%20Optuna.ipynb

**Comment by skhonsha** [comment]
I used "AAPL"!

**Comment by Athe-kunal** [comment]
Yeah maybe the hyperparameters are not optimal for Apple. So try changing the learning rate or for an automatic process follow the tutorial on Optuna

**Comment by skhonsha** [comment]
Thank you, I try it.

**Comment by skhonsha** [comment]
Dear @Athe-kunal 
after optimization and changing them in previous file, same error occurs
![errrrror](https://user-images.githubusercontent.com/40491703/141612524-5822dffe-340b-4cfa-87e1-090c537826b7.png)
!

![errrror](https://user-images.githubusercontent.com/40491703/141612541-4ea9252b-e872-442d-ac13-91a46d5135ae.png)
![errror](https://user-images.githubusercontent.com/40491703/141612547-a547a605-a339-4cf2-8de5-fbab0d77d568.png)

**Comment by Athe-kunal** [comment]
@skhonsha I am sorry actually
I did not update the tutorial. Just check if you have the same number of total_timesteps for both tuning and training. The tutorial has different because earlier I misunderstood the meaning of total_timesteps. Below is the updated one. Check and inform if they are working properly
https://colab.research.google.com/drive/1vakh33H8PMQV-msjeARhQAYtSQ-1xFN-?usp=sharing

**Comment by skhonsha** [comment]
@Athe-kunal 
It took 6 hours but the problem is still there! Can  if statement id sharpe calculation in models.py resolve?

**Comment by skhonsha** [comment]
![errrrrrrror](https://user-images.githubusercontent.com/40491703/141671113-d6cc6bcb-4710-4e71-80d9-23b7df7bcb98.png)

**Comment by Athe-kunal** [comment]
The standard deviation in total asset column is zero hence it is showing float division error. If you are comfortable, can you share your notebook so that I can have a look at it and try resolving it. Or else see if you have passed catch in study.optimize while tuning because your model is getting diverged. Also if you have included a scheduler for early stopping

**Comment by skhonsha** [comment]
thanks,
https://gist.github.com/skhonsha/da87e2595b4cae20adf59c2a3b1834df#file-finrl_hyperparameter-tuning-using-optuna-ipynb

https://gist.github.com/skhonsha/14090f6a7b3ca9cd86fef21aaa14beb5#file-untitled0-ipynb

last time, I had no error!!! without changing!

**Comment by Athe-kunal** [comment]
Alright, I tested it again but for non tuned model my model diverged and returned NaN values
https://colab.research.google.com/drive/1xyC5o2DjWYwEuiHxQWQGUiFuSyn-MnOg?usp=sharing
Probably change the variable names for non tuned models and then test. I am not entirely sure why they are giving the same results, but in my testing I got NaN results which you can look in the attached colab link

**Comment by skhonsha** [comment]
thanks for your comment.

**Comment by skhonsha** [comment]
@Athe-kunal 
would you please help me, how to fix this error? when i use only one stock, it has no error, but more than 1 stock, i got this error.
![errrr111](https://user-images.githubusercontent.com/40491703/142761660-036d6c44-fb92-43c8-83e0-6f6732c79bf0.png)

![err111](https://user-images.githubusercontent.com/40491703/142761675-0a04617b-4d32-4845-aac9-a14a54e828a2.png)

**Comment by Athe-kunal** [comment]
You can delete the rows instead of columns by passing axis=0. Actually, there is a pivot table before the dropna so you have some NaN values in the close column hence it is dropping the whole data frame.
