### ISSUE TITLE
Short sales

### ISSUE THREAD

**Issue by Abaminog** [AI4Finance-Foundation/FinRL#345]
Hello. Do I understand correctly that the DRL methods used in FinRL are only designed to trade long positions, but not short? If you look through the trading history (including training), the model always increases or decreases long positions, but never goes short.
Is there a way of trading short, or is it a fundamental issue with FinRL? Thanks!

**Comment by rayrui312** [comment]
**It's not a fundamental issue.** We will release a version that supports short-selling in the future. Here are further explanations:

In our environment settings, short selling is not allowed. However, it can be changed easily to support short selling. For example, in `env_stocktrading_np.py`, line 111:

`sell_num_shares = min(self.stocks[index], -actions[index])`

We restrict the number of shares to sell to the stocks we are holding (long position).

You can break this limitation and set a short-selling rule by yourself. Besides this line, some other codes need to change to support short-selling. But it is not a fundamental issue. We haven't released one since the specific settings, such as some parameters, still need to tune.

**Comment by Abaminog** [comment]
Thank you for your response.
It would be great to have the short selling flexibility built in because in some years (e.g. 2008, 2020,...) a long-buying strategy is almost destined to fail as it would be heavily pushing against the market trend. 
I am presuming some other lines of the code need to be adjusted because the model needs to show profit if the share price goes down on a short position.

**Comment by Athe-kunal** [comment]
Yeah, currently there is a turbulence indicator and if passes over a certain threshold then the agent will sell all shares and wait for the market to return to its stability. Maybe there we can employ a short position so that instead of being passive in a turbulent situation, it is active.

**Comment by Athe-kunal** [comment]
Alright, I got your point @Abaminog

**Comment by KaiOnGitHub** [comment]
Any news on that? I am in the process of shaping the topic for my bachelor thesis, which will most likely be in the area of algorithmic trading with DRL. Implementing short selling/leveraged trading into the Fin RL ecosystem seems like an interesting idea. Happy to discuss this on Slack if anyone invites me (I was not able to join).

**Comment by XiaoYangLiu-FinRL** [comment]
> Any news on that? I am in the process of shaping the topic for my bachelor thesis, which will most likely be in the area of algorithmic trading with DRL. Implementing short selling/leveraged trading into the Fin RL ecosystem seems like an interesting idea. Happy to discuss this on Slack if anyone invites me (I was not able to join).

What is your email to invite you?
