### ISSUE TITLE
Usage of abstract baseclass for data processors

### ISSUE THREAD

**Issue by antolu** [AI4Finance-Foundation/FinRL#392]
I was discussing a bit with @XiaoYangLiu-FinRL on slack about implementing an abstract baseclass for the data processors in finrl_meta.

The background is this, data processors like `AlpacaProcessor` and `YahooFinanceProcessor` both implenent the `download_data` method, but with different method signatures:
* `YahooFinanceProcessor.download_data(self, start_date: str, end_date: str, ticker_list: List[str], time_interval: str) -> pd.DataFrame`
* `AlpacaProcessor.download_data(self, ticker_list: Iterable[str], start_date: str, end_date: str, time_interval: str) -> pd.DataFrame`
Which is an unecessary complication, as well as the `QuantConnectEngineer` has the method `data_fetch` instead.
Additionally, in Python they are two distinct data types which may make type hinting more confusing.

My suggestion is to implement an abstract parent class, e.g. `DataProcessor` that may contain some useful common methods like `calculate_turbulence`, `clean_data` etc. that data processors like `AlpacaProcessor` and `YahooFinanceProcessor` can inherit from, and would then technically would subclass a common class.  This would also in a way "enforce" that each data processor has the same interface. The subclasses (each custom data processor) would then be able to override the parent method if custom functionality is required.

I'm working on a prototype now that essentially moves some common functions to the abstract baseclass like `calculate_turbulence`, `clean_data`, `add_vix`, `add_technical_indicators`, since they are virtually the same between the `AlpacaProcessor `and `YahooFinanceProcessor`. Though I don't understand why the df columns "close" and "adjcp" are named differently.

Let me know what you guys think.

An extra addition could be a data processor factory, e.g. `DataProcessorFactory.create_processor(name: str, **kwargs) -> DataProcessor`.

An example of the baseclass is the following:

```
import logging
from abc import ABC, abstractmethod
from typing import Iterable, Tuple, Sequence, List
from pandas import DataFrame
import pandas as pd
import numpy as np
import pytz
import exchange_calendars as tc

log = logging.getLogger(__name__)


class DataProcessor(ABC):
    def __init__(self):
        self.start: str = ''
        self.end: str = ''
        self.time_interval: str = ''

    @abstractmethod
    def download_data(self, start_date: str, end_date: str,
                      time_interval: str, ticker_list: Iterable[str]) \
            -> DataFrame:
        pass

    @staticmethod
    def get_trading_days(start: str, end: str) -> List[str]:
        nyse = tc.get_calendar("NYSE")
        df = nyse.sessions_in_range(
            pd.Timestamp(start, tz=pytz.UTC), pd.Timestamp(end, tz=pytz.UTC)
        )
        trading_days = []
        for day in df:
            trading_days.append(str(day)[:10])

        return trading_days

    def clean_data(self, df: DataFrame) -> DataFrame:
        tic_list = np.unique(df.tic.values)

        trading_days = self.get_trading_days(start=self.start, end=self.end)

        times = []
        for day in trading_days:
            NY = "America/New_York"
            current_time = pd.Timestamp(day + " 09:30:00").tz_localize(NY)
            for i in range(390):
                times.append(current_time)
                current_time += pd.Timedelta(minutes=1)

        new_df = pd.DataFrame()
        for tic in tic_list:
            tmp_df = pd.DataFrame(
                columns=["open", "high", "low", "close", "volume"], index=times
            )
            tic_df = df[df.tic == tic]
            for i in range(tic_df.shape[0]):
                tmp_df.loc[tic_df.iloc[i]["time"]] = tic_df.iloc[i][
                    ["open", "high", "low", "close", "volume"]
                ]
            for i in range(tmp_df.shape[0]):
                if str(tmp_df.iloc[i]["close"]) == "nan":
                    previous_close = tmp_df.iloc[i - 1]["close"]
                    if str(previous_close) == "nan":
                        raise ValueError
                    tmp_df.iloc[i] = [
                        previous_close,
                        previous_close,
                        previous_close,
                        previous_close,
                        0.0,
                    ]
            tmp_df = tmp_df.astype(float)
            tmp_df["tic"] = tic
            new_df = new_df.append(tmp_df)

        new_df = new_df.reset_index()
        new_df = new_df.rename(columns={"index": "time"})

        log.info("Data clean finished!")

        return new_df

    @staticmethod
    def df_to_array(df: pd.DataFrame, tech_indicator_list: Sequence[str],
                    if_vix: bool) \
            -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        df = df.copy()
        unique_ticker = df.tic.unique()
        if_first_time = True

        if len(unique_ticker) == 0:
            raise ValueError('No tickers found in dataframe.')

        for tic in unique_ticker:
            if if_first_time:
                price_array = df[df.tic == tic][["close"]].values
                tech_array = df[df.tic == tic][tech_indicator_list].values
                if if_vix:
                    turbulence_array = df[df.tic == tic]["VIXY"].values
                else:
                    turbulence_array = df[df.tic == tic]["turbulence"].values
                if_first_time = False
            else:
                price_array = np.hstack(
                    [price_array, df[df.tic == tic][["close"]].values]
                )
                tech_array = np.hstack(
                    [tech_array, df[df.tic == tic][tech_indicator_list].values]
                )

        log.info("Successfully transformed into array")
        return price_array, tech_array, turbulence_array
```

**Comment by XiaoYangLiu-FinRL** [comment]
@zhumingpassional @rayrui3rui  Since we are doing this updating, let us coordinate here.   To avoid code crush and to make the update in a lean way, I would suggest "update in the FinRL-Meta first and after public tests, merge back to FinRL".

**Comment by zhumingpassional** [comment]
The background is this, data processors like AlpacaProcessor and YahooFinanceProcessor both implenent the download_data method, but with different method signatures

Response: These may be the old version. In the new version, both  AlpacaProcessor and YahooFinanceProcessor have the same parameters in download_data: def download_data(self, ticker_list: List[str], start_date: str, end_date: str, time_interval: str) -> pd.DataFrame:

My suggestion is to implement an abstract parent class, e.g. DataProcessor that may contain some useful common methods like calculate_turbulence, clean_data etc. that data processors like AlpacaProcessor and YahooFinanceProcessor can inherit from, and would then technically would subclass a common class. This would also in a way "enforce" that each data processor has the same interface. The subclasses (each custom data processor) would then be able to override the parent method if custom functionality is required.
I'm working on a prototype now that essentially moves some common functions to the abstract baseclass like calculate_turbulence, clean_data, add_vix, add_technical_indicators, since they are virtually the same between the AlpacaProcessor and YahooFinanceProcessor.

Response:  We have build a basic class (named as basic_processor) for all data processors, including AlpacaProcessor and YahooFinanceProcessor. Now, some useful common methods like calculate_turbulence, clean_data etc, are in the basic_processor. In the next version, we will delete these functions in in data_processors (e.g., AlpacaProcessor and YahooFinanceProcessor) after we test them.

 I don't understand why the df columns "close" and "adjcp" are named differently.
Response: They are different since some stocks (e.g., at east 100 shares can be traded) may be separated to smaller parts considering of high price.  For more info, @rayrui312 can describe it since he is more familiar with it.

**Comment by antolu** [comment]
All right. It's on it's way to be implemented. Where can I find it? 
Still however, Every data processor would be it's own distinct class which may still be a bit confusing and I still suggest using a common baseclass for improved abstraction.

**Comment by zhumingpassional** [comment]
It's on it's way to be implemented. Where can I find it?
response: 
The base class is in: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/finrl_meta/data_processors/basic_processor.py
We first implement it in FinRL-meta, and then FinRL-Meta will be merged to FinRL.

Every data processor would be it's own distinct class which may still be a bit confusing and I still suggest using a common baseclass for improved abstraction.
Distinct classes only show the different implementation details, e.g., each data processor has its own download_data,  however, they can inherit from the same base class, since they have the same parameters.

**Comment by antolu** [comment]
I see, I was looking for other branches and not a separate repository. Since you basically are implementing what I suggested I will close this issue.

If you need help with the refactoring drop me a message on slack.

**Comment by zhumingpassional** [comment]
OK. Thank you for your suggestions.
