### ISSUE TITLE
FinRL_Explainable_DRL_for_Portfolio_Management_An_Empirical_Approach.ipynb

### ISSUE THREAD

**Issue by MendhikarVishal** [AI4Finance-Foundation/FinRL#407]
![Screenshot 2022-01-05 072437](https://user-images.githubusercontent.com/97139001/148148339-aa9ccc22-452d-42c6-bb52-d39303bf6e88.png)
While running the code in FinRL_Explainable_DRL_for_Portfolio_Management_An_Empirical_Approach.ipynb in Part 7 Integrated Gradient cell getting error, PF the screenshot. Thank you.

**Comment by Athe-kunal** [comment]
Just from the code, I guess maybe the error is in specifying the technical indicator list. If you are passing the default config for technical indicators, then you will have more indicators apart from macd, rsi, cci and dx. So try passing the confid.TECHNICAL_INDICATORS_LIST instead of hard coding the technical indicators.

**Comment by 16GMCN** [comment]
The error is due to the technical_indicator_list

**Comment by MendhikarVishal** [comment]
I don't exactly know where to modify the code. Can you please describe me how to do it? Thanks.

**Comment by 16GMCN** [comment]
Please refer to the latest jupyter notebook: FinRL_Explainable_DRL_For_Portfolio_Management_An_Empirical_Approach.ipynb

**Comment by alialahyari** [comment]
I ran the above Jupyter notebook (FinRL_Explainable_DRL_For_Portfolio_Management_An_Empirical_Approach.ipynb)on my task and got the following error
Thanks for guiding me
![Screenshot (96)](https://user-images.githubusercontent.com/62207040/149023114-4753405a-7d3f-483e-953a-811adddac562.png)
