### ISSUE TITLE
Short Selling

### ISSUE THREAD

**Issue by thy-hoang-nn** [AI4Finance-Foundation/FinRL#426]
Hi, 
I have a question in the paper: "Deep reinforcement learning framework to automate trading in quantitative finance" and the ensemble strategy.

Is short selling allowed in the action space when agents start to trade? If has, there exists risk associated with the impossibility to repay the share lender if the agent suffer significant losses. How can we prevent such a situation from happening or we just trade through the number of the holding of the stocks?

Can you give me some advices? Thanks a lot!

**Comment by XelHaku** [comment]
In trainnig/model is allowed. You can notice because in the action vector
you have negative values.

In the paper trading demo has conditionals to not short sell.

Short selling has the risks you mention and is not neccesary, in my
opinion, because you are gonna spend all you cash buying stocks. If not,
then one should interchange the stocks (in the model) for ones that are
more liquid and has tendencies to go Long

**Comment by thy-hoang-nn** [comment]
@XelHaku I mean action vector has the negative values when selling stocks, not relating short selling in the ensemble strategy. 
Do we need to include the condition that the cash value is constrained to be sufficiently large when a negative number of shares is owned, in order to be able to get back to a neutral position ? So that the trading agent should always be capable of paying back the share lender. At the beginning, we include the balance and number of shares own for each stock have to remain positive.

**Comment by thy-hoang-nn** [comment]
I still confused about some actions that agents have to do such as self-financing or short-selling. Should we claim that agents do not withdraw or pump money through the trading process
