### ISSUE TITLE
The Problem of using Future Information in FinRL

### ISSUE THREAD

**Issue by BruceYanghy** [AI4Finance-Foundation/FinRL#433]
I am opening an issue and summarize the concerns that FinRL is using future information.

**Survivorship bias**. It happens when we only select stocks existing in the market or in the index today. Index changes its component stocks either add stocks or remove stocks sometimes. Stocks may be removed from an index due to bad financial performance or bankruptcy. If we only select stocks existing in the market or in the index today for backtesting, then we actually filter out the companies with potential bad performance and bankruptcy, which contains future information about companies financial performance.  

What we did in [our ensemble paper ](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3690996) is that we selected the Dow 30 stocks based on the information at 2016/01/01 which is our first trade date, from this date on, the 30 stocks were fixed, this was the right way to do it. We didn't use any future information. For example, the dow 30 constituents stocks we used in the [stocktrading demo](https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_StockTrading_NeurIPS_2018.ipynb) are just for demonstrative purpose.

In real life trading, investors may check the Dow 30 list like **yearly/quarterly** and update and rebalance the stocks.

**Comment by marcipops** [comment]
I think it depends on whether you are position trading (over multiple days, weeks or even months) or intra-day trading (like myself).  For example, with the latter, if you are trading on 1m, 5m etc you don't care about whether the company exists the next day, especially if you automatically close your trades to not attract overnight charges.
Position traders will probably be more interested in fundamentals rather than technicals, and so will be reviewing their stock portfolio frequently, and would be cognisant of the survivorship bias.

**Comment by cryptocoinserver** [comment]
It definitely can introduce a bias even for intra-day trading. As the training is done on successful stocks that survived, like @BruceYanghy nicely explained. If the sample size is big enough this might not matter, but there is absolutely the possibility that the models doesn't learn to handle "failing" stocks. In other words there might be a bullish bias. You are right thought, that one can manually compensate that by adapting the stock selection frequently / adapting the selection.
