### ISSUE TITLE
关于 FinRL中 drl_agents/elegantrl/models.py 建立 DRLAgent 类的疑问

### ISSUE THREAD

**Issue by A5230171** [AI4Finance-Foundation/FinRL#439]
目前使用最新的 models.py 建立 DRLAgent 的过程中，需要再 添加 price_array, tech_array, turbulence_array （39行）

举例：agent = DRLAgent(env=env_train, price_array, tech_array, turbulence_array)

但是看了 上下文关联的 程式，还是不明白 这三个变量添加进去的含义以及之后的作用在哪里？

目前使用的环境是 env_stocktrading.py 作为股票模拟环境，但感觉好像也没有看到关联性！

![cfa76c29b1c1705176502697cb9b48a](https://user-images.githubusercontent.com/46130746/150642608-49528457-696b-4dc1-b310-8c921f9a2940.png)

**Comment by rayrui312** [comment]
In our current framework, we need to use these data arrays to initialize the environments. Since env_stocktrading.py is an old one, it uses the old framework. (Because some old notebooks and medium blogs all use this env, we will keep it for a while.) You may see the notebook https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_Compare_ElegantRL_RLlib_Stablebaseline3.ipynb for an illustration. 

我们现在的框架用这三个array去初始化环境。env_stocktrading.py这个环境比较老了，用的还是以前的框架。(因为之前的notebook和博客都是用的这个环境做展示的，我们会把这个环境保留一阵子)。你可以看下github上那个compare的notebook，里面有展示我们现在的框架。

**Comment by A5230171** [comment]
@XiaoYangLiu-FinRL 
Is there any more standard notebook example that I can refer to, because I read the FinRL notebook and feel that the version is inconsistent. I want to use the Multiple Stock Trading environment, and then I want to try MADDPG. Could you please recommend it to me! (The notebook I answered earlier is gone), thank you

请问有没有比较标准的notebook范例可以给我参考，因为我看了FinRL的notebook都感觉版本上的不一致，我是想使用Multiple Stock Trading环境，之后想再尝试MADDPG。请您给我推荐好嘛！(之前回答的notebook已经不见了)，谢谢你

**Comment by XiaoYangLiu-FinRL** [comment]
Can you try to find them in the following:
https://github.com/AI4Finance-Foundation/FinRL/tree/master/tutorials
