### ISSUE TITLE
Issue in FinRL_StockTrading_Fundamental.ipynb

### ISSUE THREAD

**Issue by fulong98** [AI4Finance-Foundation/FinRL#462]
Hi, 

I have trained the TD3 & DDPG models using fundamental data. However, i found error in this repo when I checking the logging data: df_actions. The model only bought stocks in the few first days but never sell it. (that means the model is executing buy-and-hold strategy on a few stocks).

May I know is it the same for other DRL model?
![Screenshot 2022-02-09 at 9 06 41 PM](https://user-images.githubusercontent.com/28505369/153207219-1462a0b1-7923-41bd-b26d-5c2142e01f51.png)
?

**Comment by Athe-kunal** [comment]
Did you run out of cash?
Can you check if you have enough cash to transact? Yeah it is also strange that it is not selling any stocks.

**Comment by fulong98** [comment]
i used the original settings and variables. 
That means the author did something wrong without checking the details

**Comment by Athe-kunal** [comment]
Yeah you can try increasing the initial_amount in the trading environment. See if it is still buying all the stocks upfront

**Comment by fulong98** [comment]
hmmm suppose the agent should learn how and when to sell it...

**Comment by alvaromorales1965** [comment]
I tried different things. The algorithm follows an strategy of buy and hold

**Comment by lcavalie** [comment]
Hi,

I run into the same problem with the paper trading notebook.
It turned out that 2021 (except for a short moment in September) was a year where buy and hold was a very good strategy. IT appears that during the training phase if the model find out that selling is not a good strategy it simply does not do that later on (after the training phase).
If you go with the standard $100,000 it may not be enough, after raising the amount to $1M it moved the positions a little better.
I also trained it on specific weeks (beginning of September) where selling was a good idea as opposed to October in the default parameters of the paper trading notebook, and then the model actually did some selling later on in real trading. So I don’t think it’s a bug in the code itself. I did see the model sell positions.

L
