### ISSUE TITLE
"initial_amount" in Finrl.finrl.finrl_meta.env_stock_trading.env_stocktrading.py commented out

### ISSUE THREAD

**Issue by mokzheen** [AI4Finance-Foundation/FinRL#495]
![image](https://user-images.githubusercontent.com/66867864/156475908-cb979726-3a0c-4da3-b81b-130c1feec847.png)

why is the "initial_amount" in Finrl.finrl.finrl_meta.env_stock_trading.env_stocktrading.py commented out?

**Comment by dpaiton** [comment]
It was introduced in the latest PR: https://github.com/AI4Finance-Foundation/FinRL/pull/491/files

**Comment by shenlei515** [comment]
It was for the case where you own some share of stock in the beginning day instead of only cash. @dpaiton

**Comment by Grantmiller12** [comment]
New to this environment. I noticed this change is different from the tutorials provided online so I am not sure if this error below is due to this recent change or if this is an environment error on my local machine.  
![image](https://user-images.githubusercontent.com/31163608/157115908-4a400c22-8ea8-4303-a117-335d4366f9a8.png)

**Comment by dpaiton** [comment]
@XiaoYangLiu-FinRL you marked this as closed but the bug is not resolved. With the change described above, many of the tutorials no longer work. If I search the repository for `initial_amount` then I see a lot of code that will break with the updated class definition from PR https://github.com/AI4Finance-Foundation/FinRL/pull/491

Here's the search url:
https://github.com/AI4Finance-Foundation/FinRL/search?q=initial_amount

**Comment by XiaoYangLiu-FinRL** [comment]
We recent reorganized after closing this issue！ Let us open it to fix it.

**Comment by italodamato** [comment]
Hey all - I'm trying to run the tutorial mentioned above. Does this fix work as expected:
from
```
 "initial_amount": 1000000, 
```
to
```
 "initial_list": [1000000, 1000000], 
```

**Comment by zhumingpassional** [comment]
Please see the newest version.

Fixed.
