### ISSUE TITLE
ModuleNotFoundError: No module named 'elegantrl.config'      (from elegantrl.config import Arguments)

### ISSUE THREAD

**Issue by yizhangliu** [AI4Finance-Foundation/FinRL#508]
In elegantrl v0.3.3,   ' from elegantrl.run import Arguments'  is ok.

**Comment by yizhangliu** [comment]
Elegentrl has changed frequently recently. Please keep consistent with it or indicate the corresponding version in requirements.txt.
Thanks a lot.

**Comment by zhumingpassional** [comment]
Please try 
from elegantrl.train.config import Arguments

**Comment by XiaoYangLiu-FinRL** [comment]
Sorry that ElegantRL is actively updating.  I also notice many issues/bugs. 
Thanks for your feedback.  I am asking every team member to follow standard workflow closely, reducing the troubles.
We also welcome your help.

**Comment by Yonv1943** [comment]
We apologize for the recent changes because we want to add support for vectorized env and compatibility with single env. 
This pull request fix this bug.
[Fix bug for vec env and agentbase init # 248](https://github.com/AI4Finance-Foundation/ElegantRL/pull/248)

Along with this update, we will be updating the unit tests module to help us stabilize the API.
[Add Unit tests for elegantrl.agents # 254](https://github.com/AI4Finance-Foundation/ElegantRL/pull/254)

**Comment by ali-meesam23** [comment]
Not sure why this was closed. The issue still persists. I am new to the community will appreciate any guidance on how ot resolve this. Thank you!
![Screenshot 2023-08-17 at 6 01 44 PM](https://github.com/AI4Finance-Foundation/FinRL/assets/46407467/283dceb9-cffc-4387-8424-e1a2a04f02fe)
