### ISSUE TITLE
Why do we use technical indicators as input to RL training? 

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL#578]
What are the reasons we use technical indicators as input to RL?

Aren't these indicators human-made patterns to help humans predict and are very much open to interpretation?

Would it not be best NOT to deflect the RL by these human-made patterns, but leave the RL to work out its own patterns on the raw trading data?

**Comment by anthonyrom** [comment]
Wouldn't you rather have RL detect patterns simultaneously in raw price data as well as the coinciding technical indicators? The indicators themselves are not recognized patterns, and the RL does not implement a human-designed strategy based on interpreting them. RL may find a new way to use an indicator that a human has not seen, especially when taking many indicators as inputs.

**Comment by marcipops** [comment]
Hi @anthonyrom - thanks!  Tbh not sure as I am not an RL expert, just posing the question/suggestion.  Has anyone run an experiment to compare and contrast what RL predicts with and without technical indicators, to see if they influence the results positively or negatively?

**Comment by Athe-kunal** [comment]
Hi @marcipops 
In my [blogpost](https://medium.com/mlearning-ai/google-trends-data-for-automated-stock-trading-using-reinforcement-learning-9c0fd6d00678#5c9c), in the RESULTS and DISCUSSION section you can see that I tested out the agent performance with OHLCV data and OHLCV+TI data. You can see the account value charts and Sharpe ratio values. Here is the GitHub [link](https://github.com/Athe-kunal/Reinforcement-learning-trading-agent-using-Google-trends-data) for the project.

FEW CAVEATS
1. Generally RL algorithms are tested with multiple seed values and the average value is taken into consideration. But here I did with one seed value. So the testing is not very rigorous
2. I did Hyperparameter optimization for each case

**Comment by marcipops** [comment]
Interesting.  What was your conclusion and recommendations?

**Comment by Athe-kunal** [comment]
Technical Indicators are feature engineering. Generally, we have some heuristics for technical indicators, like if RSI is beyond this threshold, then it is oversold. So rather than explicitly mentioning this, we will train our model to figure out this and it will be dynamic, not hardcoded
In my testing, if we keep aside the caveats like the seed values, the state space with technical indicators gave better results. You can see the results [here](https://medium.com/mlearning-ai/google-trends-data-for-automated-stock-trading-using-reinforcement-learning-9c0fd6d00678#5c9c).
