### ISSUE TITLE
ImportError: cannot import name 'config' from 'finrl.config'

### ISSUE THREAD

**Issue by BreakingDusk397** [AI4Finance-Foundation/FinRL#649]
I get this error after following the [Ubuntu installation guide](https://finrl.readthedocs.io/en/latest/start/installation.html) and using the code from this [guide.](https://towardsdatascience.com/finrl-for-quantitative-finance-tutorial-for-multiple-stock-trading-7b00763b7530)

The code that causes the error:
```
# import packages
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')
import datetime

from finrl.config import config
from finrl.marketdata.yahoodownloader import YahooDownloader
from finrl.preprocessing.preprocessors import FeatureEngineer
from finrl.preprocessing.data import data_split
from finrl.env.environment import EnvSetup
from finrl.env.EnvMultipleStock_train import StockEnvTrain
from finrl.env.EnvMultipleStock_trade import StockEnvTrade
from finrl.model.models import DRLAgent
from finrl.trade.backtest import BackTestStats, BaselineStats, BackTestPlot, backtest_strat, baseline_strat
from finrl.trade.backtest import backtest_strat, baseline_strat

import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)
```

The error:
```
Traceback (most recent call last):
  File "anaconda3/envs/FinRL/lib/python3.9/site-packages/finrl/FinRL.py", line 9, in <module>
    from finrl.config import config
ImportError: cannot import name 'config' from 'finrl.config'
```

**Comment by zhumingpassional** [comment]
pls revise it to " from config import xxx'

**Comment by yuchichen286** [comment]
Hi @Xiao-Yang, I also have this error.  After using the" from config import config", the error is: No module named 'config'; What's more, it seems like I cannot use any function in finrl because the EnvSetup is also not is not defined. Could you help me to fix it? thx~~

In fact, I followed all process in the [https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159](url) with windows and there is only one error which is about box2d.py (did not run successfully).

**Comment by zhumingpassional** [comment]
do you run the codes in your local computer, or colab? 
if in your local computer, have you set the source root?

**Comment by yuchichen286** [comment]
> 

Thank you for your reply. I have check the sys.path and the clone path is in the source root. And I have run it again, it still shows that ModuleNotFoundError: No module named 'config'.

Maybe is it because I cannot do this process: Open Jupyter Notebook by typing ‘jupyter notebook’ in your ubuntu terminal, or I download the pip install finrl before?

Could you please help me~~Thank you~
