### ISSUE TITLE
Why we are not using all the informations available in the states of StockTradingEnv?

### ISSUE THREAD

**Issue by PaulchauvinAI** [AI4Finance-Foundation/FinRL#680]
I am wondering why we don't take into account  important features like  "volume", "high" and "low" in the state of StockTradingEnv.
Are these informations already in the tech indicators or in the turbulence variable ? 
If no, have you already tested the models with these extra informations?

**Comment by zhumingpassional** [comment]
Three arrays (price_array, tech_array, turbulence_array) are used as info. 
"volume", "high" and "low" are in price_array

**Comment by PaulchauvinAI** [comment]
Thanks for the quick reply! I don't see the "volume", "high" and "low" (or price_array) in the implementation of StockTradingEnv(gym.Env) in 
[https://github.com/AI4Finance-Foundation/FinRL/blob/5ac9005643120903c3bbe869687d27b6b16c37a8/finrl/meta/env_stock_trading/env_stocktrading.py#L416].
The state corresponds here to ["cash", "close", "num_share", "tech indicators"]. Is this script outdated?

<img width="694" alt="Capture d’écran 2022-07-19 à 15 44 31" src="https://user-images.githubusercontent.com/97964230/179766199-7d92eccb-d0a9-4ed0-8379-d0f5993dd588.png">

**Comment by PaulchauvinAI** [comment]
Yes that's why I find it weird that only self.data.close and self.data[tech] are used here.

**Comment by XiaoYangLiu-FinRL** [comment]
The reason is that in our testing, we do not see "its contribution", so we did not add volume, and only include close price;  not OHL prices.

In principle, all information can be used in the "state".  In practice, you can do some correlation analysis and put uncorrelated features into a state.  Currently, I do not know a systematic way, let us know if you have a better solution.  Thanks in advance.

**Comment by PaulchauvinAI** [comment]
I see! Thanks a lot for your answer, I'm gonna have a look at the papers
