### ISSUE TITLE
Buy action should have time leagacy, the predicted action at time T show be acted in time T + 1

### ISSUE THREAD

**Issue by wingmor99** [AI4Finance-Foundation/FinRL#877]
The line 
                buy_amount = (
                    self.state[index + 1] * buy_num_shares * (1 + self.buy_cost_pct)
                )
in the file env_stocktrading_China_A_shares.py. 

Does it means we buy the stock at time T based on the predicted action at time T?

**Comment by oliverwang15** [comment]
Hi, wingmor99. Actually, we haven't considered the 'T+1' trading system at first because there are methods to avoid buying and selling the same stock like holding some shares of each stock at the beginning and only trading on parts of them. However, your suggestion is quite meaningful and we will update the China A shares environment soon with the consideration of the 'T+1' trading system.

**Comment by wingmor99** [comment]
@oliverwang15 Thanks for the explanation. Looking forward to the update ~
